---
title: "STAT 574 Midterm R"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Problem 1
# k-nearest neighborhood regression - compute prediction accuracy 10,15, 20%
# plot acutal and predicted values in same coordinate system

hospital <- read.csv("C:/Users/saedw/OneDrive/Desktop/STAT 574 Data Mining/HW1STAT574S23/DATA SETS/hospital_data.csv")

# split data 80% train 20% test
set.seed(1094543)
sample <- sample(c(TRUE, FALSE), nrow(hospital), replace=TRUE, prob = c(0.8,0.2))
train <- hospital[sample,]
test <- hospital[!sample,]

View(hospital)

train.x<- data.matrix(train[-7])
train.y<- data.matrix(train[7])
test.x<- data.matrix(test[-7])
test.y<- data.matrix(test[7])



#TRAINING K-NEAREST NEIGHBOR REGRESSION 
library(caret)
print(train(surgery_cost ~ gender + age + ASA + BMI + surgery_duration_min,
            data=train, method="knn"))

#FITTING OPTIMAL KNN REGRESSION (K=9)
knn.reg<- knnreg(train.x, train.y, k=9)

#COMPUTING PREDICTION ACCURACY FOR TESTING DATA 
pred.y<- predict(knn.reg, test.x)


#COMPUTING PREDICTION ACCURACY FOR TESTING DATA 
pred.y<- predict(knn.reg, test.x)

#accuracy within 10%
accuracy10<- ifelse(abs(test.y-pred.y)<0.10*test.y,1,0) 
print(mean(accuracy10))

#accuracy within 15%
accuracy15<- ifelse(abs(test.y-pred.y)<0.15*test.y,1,0) 
print(mean(accuracy15))

#accuracy within 20%
accuracy20<- ifelse(abs(test.y-pred.y)<0.20*test.y,1,0) 
print(mean(accuracy20))

#PLOTTING ACTUAL AND RPEDICTED VALUES FOR TESTING DATA
x<- 1:length(test.y)
plot(x, test.y, type="l", lwd=2, col="magenta", main="KNN Regression", 
panel.first=grid())
lines(x, pred.y, lwd=2, col="dodgerblue")
legend("topright", c("actual", "predicted"), lty=1, lwd=2,
col=c("magenta","dodgerblue"))
```


```{r}
# Problem 2
# fit k-nearest neighbor binary classifier
# compute prediction accuracy

credit_data <- read.csv("C:/Users/saedw/OneDrive/Desktop/STAT 574 Data Mining/HW1STAT574S23/DATA SETS/card_transdata.csv")


View(credit_data)

# split data 80% train 20% test
set.seed(6749379)
sample <- sample(c(TRUE,FALSE), nrow(credit_data), replace=TRUE, 
                 prob=c(0.8,0.2))
train <- credit_data[sample,]
test <- credit_data[!sample,]

train.x<- data.matrix(train[-8])
train.y<- data.matrix(train[8])
test.x<- data.matrix(test[-8])
test.y<- data.matrix(test[8])


#TRAINING K-NEAREST NEIGHBOR BINARY CLASSIFIER
library(caret)
print(train(as.factor(fraud)~., data=train, method="knn"))

#FITTING OPTIMAL KNN BINARY CLASSIFIER (K=9)
knn.class<- knnreg(train.x, train.y, k=9)

#COMPUTING PREDICTION ACCURACY FOR TESTING DATA 
pred.prob<- predict(knn.class, test.x)

len<- length(pred.prob)
pred.y<- c()
match<- c()
for (i in 1:len){
  pred.y[i]<- ifelse(pred.prob[i]>=0.5, 1,0)
  match[i]<- ifelse(test.y[i]==pred.y[i], 1,0)
}
print(paste("accuracy=",round(mean(match),digits=4)))

#alternative (frugal) way
pred.y1<- floor(0.5+predict(knn.class, test.x))
print(paste("accuracy=", round(1-mean(test.y!=pred.y1),digits=4)))

```



```{r}
# Problem 3
# k-nearest neighbor multinomial classification
# compute prediction accuracy

concuss <- read.csv("C:/Users/saedw/OneDrive/Desktop/STAT 574 Data Mining/HW1STAT574S23/DATA SETS/concussions_data.csv")

# split data 80% train 20% test
set.seed(898323)
sample <- sample(c(TRUE,FALSE), nrow(concuss), replace=TRUE,
                 prob=c(0.8,0.2))
train <- concuss[sample,]
test <- concuss[!sample,]

train.x<- data.matrix(train[-5])
train.y<- data.matrix(train[5])
test.x<- data.matrix(test[-5])
test.y<- data.matrix(test[5])


#FITTING K-NEAREST NEIGHBOR MULTINOMIAL CLASSIFIER 
#k=3 reasonably maximizes prediction accuracy for testing set
library(caret)
knn.mclass<- knnreg(train.x, train.y, k=3)

#COMPUTING PREDICTION ACCURACY FOR TESTING DATA 
pred.y<- round(predict(knn.mclass, test.x), digits=0)
print(paste("accuracy=", round(1-mean(test.y!=pred.y),digits=4)))


```



```{r}
# Problem 4
# fit support vector regression with linear, polynomial, radial, and sigmoid
  # kernals - compute prediction accuracy 10, 15, 20% - choose best fitted model

hospital <- read.csv("C:/Users/saedw/OneDrive/Desktop/STAT 574 Data Mining/HW1STAT574S23/DATA SETS/hospital_data.csv")


# split data 80% train 20% test
set.seed(1094543)
sample <- sample(c(TRUE, FALSE), nrow(hospital), replace=TRUE, prob = c(0.8,0.2))
train <- hospital[sample,]
test <- hospital[!sample,]

test.x<- data.matrix(test[-7])
test.y<- data.matrix(test[7])


library(e1071)

#FITTING SVR WITH LINEAR KERNEL #######################################
svm.reg<- svm(surgery_cost ~ age + gender + BMI + ASA + surgery_duration_min,
              data=train, kernel="linear")

#COMPUTING PREDICTION ACCURACY FOR TESTING DATA 
pred.y<- predict(svm.reg, test)

#accuracy within 10%
accuracy10<- ifelse(abs(test.y-pred.y)<0.10*test.y,1,0) 

#accuracy within 15%
accuracy15<- ifelse(abs(test.y-pred.y)<0.15*test.y,1,0) 

#accuracy within 20%
accuracy20<- ifelse(abs(test.y-pred.y)<0.20*test.y,1,0)

print('Linear Kernel')
print(paste('within 10%:', round(mean(accuracy10),4)))
print(paste('within 15%:', round(mean(accuracy15),4)))
print(paste('within 20%:', round(mean(accuracy20),4)))


#FITTING SVR WITH POLYNOMIAL KERNEL ######################################
svm.reg<- svm(surgery_cost ~ age + gender + BMI + ASA + surgery_duration_min,
              data=train, kernel="poly")

#COMPUTING PREDICTION ACCURACY FOR TESTING DATA 
pred.y<- predict(svm.reg, test)

#accuracy within 10%
accuracy10<- ifelse(abs(test.y-pred.y)<0.10*test.y,1,0) 

#accuracy within 15%
accuracy15<- ifelse(abs(test.y-pred.y)<0.15*test.y,1,0) 

#accuracy within 20%
accuracy20<- ifelse(abs(test.y-pred.y)<0.20*test.y,1,0)

print('Polynomial Kernel')
print(paste('within 10%:', round(mean(accuracy10),4)))
print(paste('within 15%:', round(mean(accuracy15),4)))
print(paste('within 20%:', round(mean(accuracy20),4)))

#FITTING SVR WITH RADIAL KERNEL #######################################
svm.reg<- svm(surgery_cost ~ age + gender + BMI + ASA + surgery_duration_min,
              data=train, kernel="radial")

#COMPUTING PREDICTION ACCURACY FOR TESTING DATA 
pred.y<- predict(svm.reg, test)

#accuracy within 10%
accuracy10<- ifelse(abs(test.y-pred.y)<0.10*test.y,1,0) 

#accuracy within 15%
accuracy15<- ifelse(abs(test.y-pred.y)<0.15*test.y,1,0) 

#accuracy within 20%
accuracy20<- ifelse(abs(test.y-pred.y)<0.20*test.y,1,0)

print('Radial Kernel')
print(paste('within 10%:', round(mean(accuracy10),4)))
print(paste('within 15%:', round(mean(accuracy15),4)))
print(paste('within 20%:', round(mean(accuracy20),4)))

#FITTING SVR WITH SIGMOID KERNEL ####################################
svm.reg<- svm(surgery_cost ~ age + gender + BMI + ASA + surgery_duration_min,
              data=train, kernel="sigmoid")

#COMPUTING PREDICTION ACCURACY FOR TESTING DATA 
pred.y<- predict(svm.reg, test)

#accuracy within 10%
accuracy10<- ifelse(abs(test.y-pred.y)<0.10*test.y,1,0) 

#accuracy within 15%
accuracy15<- ifelse(abs(test.y-pred.y)<0.15*test.y,1,0) 

#accuracy within 20%
accuracy20<- ifelse(abs(test.y-pred.y)<0.20*test.y,1,0)

print('Sigmoid Kernel')
print(paste('within 10%:', round(mean(accuracy10),4)))
print(paste('within 15%:', round(mean(accuracy15),4)))
print(paste('within 20%:', round(mean(accuracy20),4)))


```



```{r}
# Problem 5
# support vector binary classifier with linear, polynomial, radial, and sigmoid
  # kernals and compute prediction accuracy


credit_data <- read.csv("C:/Users/saedw/OneDrive/Desktop/STAT 574 Data Mining/HW1STAT574S23/DATA SETS/card_transdata.csv")

View(credit_data)

# split data 80% train 20% test
set.seed(482044)
sample <- sample(c(TRUE, FALSE), nrow(credit_data), replace=TRUE,
                 prob = c(0.8,0.2))
train <- credit_data[sample,]
test <- credit_data[!sample,]

train.x<- data.matrix(train[-8])
train.y<- data.matrix(train[8])
test.x<- data.matrix(test[-8])
test.y<- data.matrix(test[8])

library(e1071)


#FITTING SVM WITH LINEAR KERNEL #############################################
svm.class<- svm(as.factor(fraud) ~ ., data=train, kernel="linear")

#computing prediction accuracy for testing data
pred.y<- as.numeric(predict(svm.class, test.x))-1

for (i in 1:length(pred.y))
  match[i]<- ifelse(test.y[i]==pred.y[i], 1,0)
print(paste("accuracy=", round(mean(match), digits=4)))


#FITTING SVM WITH Polynomial KERNEL ###########################################
svm.class<- svm(as.factor(fraud) ~ ., data=train, kernel="polynomial")

#computing prediction accuracy for testing data
pred.y<- as.numeric(predict(svm.class, test.x))-1

for (i in 1:length(pred.y))
  match[i]<- ifelse(test.y[i]==pred.y[i], 1,0)
print(paste("accuracy=", round(mean(match), digits=4)))

#FITTING SVM WITH radial KERNEL ###########################################
svm.class<- svm(as.factor(fraud) ~ ., data=train, kernel="radial")

#computing prediction accuracy for testing data
pred.y<- as.numeric(predict(svm.class, test.x))-1

for (i in 1:length(pred.y))
  match[i]<- ifelse(test.y[i]==pred.y[i], 1,0)
print(paste("accuracy=", round(mean(match), digits=4)))

#FITTING SVM WITH sigmoid KERNEL ###########################################
svm.class<- svm(as.factor(fraud) ~ ., data=train, kernel="sigmoid")

#computing prediction accuracy for testing data
pred.y<- as.numeric(predict(svm.class, test.x))-1

for (i in 1:length(pred.y))
  match[i]<- ifelse(test.y[i]==pred.y[i], 1,0)
print(paste("accuracy=", round(mean(match), digits=4)))


```



```{r}
# Problem 6
# support vector multinomial classification
 # same kernals as above and compute prediction accuracy for each

concuss <- read.csv("C:/Users/saedw/OneDrive/Desktop/STAT 574 Data Mining/HW1STAT574S23/DATA SETS/concussions_data.csv")


#SPLITTING DATA INTO 80% TRAINING AND 20% TESTING SETS 
set.seed(444625)
sample <- sample(c(TRUE, FALSE), nrow(concuss), replace=TRUE, prob=c(0.8,0.2))
train<- concuss[sample,]
test<- concuss[!sample,]

train.x<- data.matrix(train[-5])
train.y<- data.matrix(train[5])
test.x<- data.matrix(test[-5])
test.y<- data.matrix(test[5])


library(e1071)

#FITTING SVM WITH LINEAR KERNEL ###########################################
svm.multiclass<- svm(as.factor(concussion) ~ ., data=train, kernel="linear")

#computing prediction accuracy for testing data
pred.y<- as.numeric(predict(svm.multiclass, test))

print(paste("accuracy=", round(1-mean(test.y!=pred.y), digits=4)))


#################################################################
#FITTING SVM WITH POLYNOMIAL KERNEL
svm.multiclass<- svm(as.factor(concussion) ~ ., data=train, kernel="polynomial")

#computing prediction accuracy for testing data
pred.y<- as.numeric(predict(svm.multiclass, test))

print(paste("accuracy=", round(1-mean(test.y!=pred.y), digits=4)))


#################################################################
#FITTING SVM WITH RADIAL KERNEL
svm.multiclass<- svm(as.factor(concussion) ~ ., data=train, kernel="radial")

#computing prediction accuracy for testing data
pred.y<- as.numeric(predict(svm.multiclass, test))

print(paste("accuracy=", round(1-mean(test.y!=pred.y), digits=4)))

#################################################################
#FITTING SVM WITH SIGMOID KERNEL
svm.multiclass<- svm(as.factor(concussion) ~ ., data=train, kernel="sigmoid")

#computing prediction accuracy for testing data
pred.y<- as.numeric(predict(svm.multiclass, test))

print(paste("accuracy=", round(1-mean(test.y!=pred.y),digits=4)))

```

